### ISSUE TITLE
End portals go into the void

### ISSUE THREAD

**Issue by Goel25** [Multiverse/Multiverse-NetherPortals#119]
My worlds:

```
[Server] INFO Islands_the_end - THE_END
[Server] INFO Islands - NORMAL
[Server] INFO Mine - NORMAL
[Server] INFO Islands_nether - NETHER
[Server] INFO ====[ Multiverse World List ]====
```

```
My MvNP config:
bounceback: true
worlds:
  Islands:
    portalgoesto:
      NETHER: Islands_nether
      END: Islands_the_end
  Mine:
    portalgoesto:
      NETHER: Islands_nether
      END: Islands_the_end
```

When I go into an end portal in the world "Mine" it takes me to an empty area in "Islands_the_end" if I go into an end portal in "Islands" it just makes a really loud noise and doesn't take me anywhere... I have no idea what is wrong.
