### ISSUE TITLE
Portals doesnt send players to their linked worlds [1.16.2]

### ISSUE THREAD

**Issue by rockrevenchy** [Multiverse/Multiverse-NetherPortals#173]
Greetings! I scratched my head for a little over 3 hours now to find anything related to this issue or a solution to it to no avail, so here I am!

I use the snapshot 4.1.1 for both multiverse and mv-netherportal

I have 5 worlds which are really self explanatory: spawn, nether, end, skyblock, spawn_the_end (cant remove it)
no matter how I link my portals, they do not send me anywhere but (after activating Debug) the console gets spammed with this entry bellow upon using the portal but I remain still and dont get sent anywhere
`[Multiverse-NetherPortals-Debug]: Finding new teleport location for player RockRevenchy to world nether`

This bellow is how my configs are set
```
bounceback: true
worlds:
  skyblock:
    portalgoesto:
      END: end
      NETHER: nether
  nether:
    portalgoesto:
      NETHER: skyblock
  end:
    portalgoesto:
      END: spawn
```
Spigot: git-Spigot-379750e-9a9c223 (MC: 1.16.2)
/mv version: https://pastebin.com/Fe3J7vKH (/mv version -b wouldnt give me a link)

**Comment by rockrevenchy** [comment]
also to be noted, the end portal sends me to "spawn_the_end" instead of "end"

**Comment by rockrevenchy** [comment]
I figured the nether portals part, this setting is server.properties has to be like this allow-nether=true
altho the end portal still sends players to the wrong world

**Comment by nicegamer7** [comment]
There is a similar setting for the end in `bukkit.yml` called `allow-end`. Please check it's value and get back to us.

**Comment by rockrevenchy** [comment]
if `allow-end` is at false, it simply wont send the player anywhere but it does show this in the console
`[Multiverse-NetherPortals-Debug]: Finding new teleport location for player RockRevenchy to world end`

**Comment by PopcornMadness** [comment]
I am having the same problem.  Reverting back to 1.16.1 seems to fix the issue.

**Comment by shroomdog27** [comment]
Right so this issue also effects end portals. On a server I manage, there's the `hub` world, which is the main world in `server.properties` and another world called `survival_world`. The `hub` has the child worlds `hub_nether` and `hub_the_end`. You are in another world called `survival_world` that has `survival_end` and `survival_nether`. If you enter a stronghold portal from `survival` you end up in `hub_the_end` despite your config linking `survival_world` to `survival_end`. Here's our config.

```yaml
bounceback: true
worlds:
  survival_world:
    portalgoesto:
      NETHER: survival_nether
      END: survival_end
```
In addition, if you manage to get to the `survival_end` via some other means, if you enter the return portal, it tries to send you to `survival_end_the_end` which ends up sending you to `hub_the_end` anyway. And in `hub_the_end`, it just spams you `You have no home bed or charged respawn anchor, or it was obstructed` everytime you try to enter it and puts you at `0, 67, 0` in the same world.
